### ISSUE TITLE
Allow the client to unlock

### ISSUE THREAD

**Issue by IcanDivideBy0** [lemonde/primus-locky#2]
Once a client has locked a resource, he can't unlock it without leaving the room.

**Comment by neoziro** [comment]
@IcanDivideBy0 give me the rights and I will transfer this repository to Le Monde.

**Comment by IcanDivideBy0** [comment]
@neoziro so you don't maintain this project anymore ?

**Comment by neoziro** [comment]
@IcanDivideBy0 nop, just locky

**Comment by IcanDivideBy0** [comment]
:'(
